name: deploy-non-prd
on:
  push:
    branches:
      - dev
      - master
env:
  ENV_NAME: ${{ env.ENV_NAME }}      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
        